const $=s=>document.querySelector(s);
const state={papers:[],meta:{},topic:'すべて',feedback:JSON.parse(localStorage.getItem('urocatFeedback')||'{}')};
const fmtDate=s=>{if(!s||s==='0000-01-01')return '日付不明';const d=new Date(s+'T00:00:00');return isNaN(d)?s:new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'short',day:'numeric'}).format(d)};
const stars=n=>'★'.repeat(Number(n)||1)+'☆'.repeat(5-(Number(n)||1));
const score=p=>Number(p.final_score||p.relevance_score||1);
const fb=id=>state.feedback[id]||{};
function saveFeedback(){localStorage.setItem('urocatFeedback',JSON.stringify(state.feedback));render();}
function textIndex(p){return [p.title,p.japanese_title,p.abstract,p.journal,p.one_line_ja,p.main_finding_ja,p.why_relevant_ja,(p.relevance_reasons||[]).join(' ')].join(' ').toLowerCase()}
function filtered(){const q=$('#q').value.trim().toLowerCase(), min=Number($('#scoreFilter').value), rf=$('#readFilter').value;return state.papers.filter(p=>{const f=fb(p.pmid);if(score(p)<min)return false;if(state.topic!=='すべて'&&p.topic!==state.topic)return false;if(q&&!textIndex(p).includes(q))return false;if(rf==='unread'&&f.read)return false;if(rf==='favorite'&&!f.favorite)return false;if(rf==='relevant'&&f.vote!=='relevant')return false;return true}).sort((a,b)=>score(b)-score(a)||String(b.publication_date).localeCompare(String(a.publication_date)))}
function renderTopics(){const topics=['すべて',...new Set(state.papers.map(p=>p.topic).filter(Boolean))];$('#topicChips').innerHTML=topics.map(t=>`<button class="chip ${t===state.topic?'active':''}" data-topic="${escapeHtml(t)}">${escapeHtml(t)}</button>`).join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;render()})}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){renderTopics();const list=filtered();$('#resultCount').textContent=`${list.length}報を表示`;const root=$('#papers');root.innerHTML='';if(!list.length){root.innerHTML='<div class="empty card">条件に一致する論文はありません。</div>';return}for(const p of list){const node=$('#paperTemplate').content.firstElementChild.cloneNode(true), f=fb(p.pmid);if(f.read)node.classList.add('is-read');node.querySelector('.badges').innerHTML=`<span class="badge score">${stars(score(p))}</span><span class="badge">${escapeHtml(p.topic||'未分類')}</span>`;node.querySelector('time').textContent=fmtDate(p.publication_date);node.querySelector('.title').textContent=p.title||'';node.querySelector('.ja-title').textContent=p.japanese_title||'';node.querySelector('.meta').textContent=[p.journal,(p.authors||[]).slice(0,2).join(', ')+(p.authors?.length>2?' et al.':''),p.pmid?`PMID ${p.pmid}`:''].filter(Boolean).join('｜');node.querySelector('.summary').textContent=p.one_line_ja||p.why_relevant_ja||'Abstractを開いて確認してください。';node.querySelector('.pubmed').href=p.pubmed_url||'#';const rel=node.querySelector('.relevant'),irr=node.querySelector('.irrelevant'),fav=node.querySelector('.favorite');if(f.vote==='relevant')rel.classList.add('on');if(f.vote==='irrelevant')irr.classList.add('on');if(f.favorite){fav.classList.add('on');fav.textContent='★'}node.querySelector('.open').onclick=()=>openPaper(p);rel.onclick=()=>{state.feedback[p.pmid]={...f,vote:f.vote==='relevant'?null:'relevant'};saveFeedback()};irr.onclick=()=>{state.feedback[p.pmid]={...f,vote:f.vote==='irrelevant'?null:'irrelevant'};saveFeedback()};fav.onclick=()=>{state.feedback[p.pmid]={...f,favorite:!f.favorite};saveFeedback()};root.appendChild(node)}}
function section(title,text){if(!text)return'';return `<section class="detail-section"><h4>${escapeHtml(title)}</h4><p>${escapeHtml(text)}</p></section>`}
function openPaper(p){state.feedback[p.pmid]={...fb(p.pmid),read:true};localStorage.setItem('urocatFeedback',JSON.stringify(state.feedback));$('#dialogBody').innerHTML=`<div class="badges"><span class="badge score">${stars(score(p))}</span><span class="badge">${escapeHtml(p.topic||'')}</span></div><h2>${escapeHtml(p.title)}</h2>${p.japanese_title?`<h3>${escapeHtml(p.japanese_title)}</h3>`:''}<div class="meta">${escapeHtml([p.journal,fmtDate(p.publication_date),`PMID ${p.pmid}`].filter(Boolean).join('｜'))}</div><div class="detail-grid"><div class="detail-box"><small>対象</small>${escapeHtml(p.population||'Abstractから自動抽出なし')}</div><div class="detail-box"><small>研究デザイン</small>${escapeHtml(p.study_design||((p.publication_types||[]).join(', ')||'不明'))}</div></div>${section('ひとことで',p.one_line_ja)}${section('主な結果',p.main_finding_ja)}${section('研究との関連',p.why_relevant_ja)}${section('Abstract（PubMed原文）',p.abstract||'Abstract未登録')}${section('選別理由',(p.relevance_reasons||[]).join(' / '))}<div class="dialog-links"><a href="${escapeHtml(p.pubmed_url||'#')}" target="_blank" rel="noopener">PubMed</a>${p.doi_url?`<a href="${escapeHtml(p.doi_url)}" target="_blank" rel="noopener">DOI</a>`:''}</div>`;$('#paperDialog').showModal();render()}
async function load(){try{const [papers,meta]=await Promise.all([fetch('./data/papers.json?'+Date.now()).then(r=>r.json()),fetch('./data/state.json?'+Date.now()).then(r=>r.json())]);state.papers=Array.isArray(papers)?papers:papers.papers||[];state.meta=meta||{};$('#updatedAt').textContent=meta.updated_at&&meta.updated_at!=='demo'?new Date(meta.updated_at).toLocaleString('ja-JP'):'デモ';$('#totalCount').textContent=state.papers.length;$('#highCount').textContent=state.papers.filter(p=>score(p)>=4).length;render()}catch(e){console.error(e);$('#papers').innerHTML='<div class="empty card">データを読み込めませんでした。GitHub Pagesの公開設定を確認してください。</div>'}}
['q','scoreFilter','readFilter'].forEach(id=>$('#'+id).addEventListener(id==='q'?'input':'change',render));$('#resetBtn').onclick=()=>{$('#q').value='';$('#scoreFilter').value='4';$('#readFilter').value='all';state.topic='すべて';render()};$('#closeDialog').onclick=()=>$('#paperDialog').close();$('#paperDialog').addEventListener('click',e=>{if(e.target===$('#paperDialog'))$('#paperDialog').close()});$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state.feedback,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='urocat-feedback.json';a.click();URL.revokeObjectURL(a.href)};
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
load();
